CONTIKI_PROJECT = demo
all: $(CONTIKI_PROJECT)

#MODULES += os/services/shell
# CONTIKI_TARGET_SOURCEFILES += board-buttons.c
#MAKE_MAC = MAKE_MAC_TSCH
#MODULES += os/services/rpl-border-router

CONTIKI = ../..
include $(CONTIKI)/Makefile.include